---
title: "Stats Tutorials"
author: "Albert Yeh"
date: "12/17/2023"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r libraries, include = FALSE}
#install.packages("pwr")
#install.packages("tidyr")
#install.packages("ggplot2")
```


```{r library load, echo=FALSE, results='hide'}
library(pwr)
library(tidyr)
library(ggplot2)
library(dplyr)
```

## Part 1: An Interactive Follow-up

We will take a look at this again using an interactive approach, where you can vary the effect size "Cohen's d". For this tutorial, we will enable 2 simultaneous inputs so we can compare two scenarios.
```{r echo = FALSE}
sliderInput("p_value",
  label = "Significance level (alpha):",
  min = 0,
  max = 1,
  value = 0.05,
  step = 0.005)

sliderInput("cohens_d",
  label = "Plot 1: Cohen's d (effect size):",
  min = 0,
  max = 2,
  value = 0.2,
  step = 0.05)

sliderInput("cohens_d2",
  label = "Plot 2: Cohen's d:",
  min = 0,
  max = 2,
  value = 0.8,
  step = 0.05)
```

```{r echo = FALSE}
renderPlot({
  effect_sizes <- c(input$cohens_d, input$cohens_d2) 
  sample_sizes = seq(10, 500, 10)
  p_values <- input$p_value
  
  input_df <- crossing(effect_sizes,sample_sizes,p_values)
  
  get_power <- function(df){
  power_result <- pwr.t.test(n=df$sample_sizes, 
                             d=df$effect_sizes,
                             sig.level=p_values,
                             power=NULL,
                             type='two.sample')
  df$power=power_result$power
  return(df)
}
  
  power_curves <- input_df %>%
    do(get_power(.)) %>%
    mutate(effect_sizes = as.factor(effect_sizes)) 
  
  ggplot(power_curves, 
       aes(x=sample_sizes,
           y=power, 
           linetype=effect_sizes)) + 
  geom_line() + 
  geom_hline(yintercept = 0.8, 
             linetype='dotdash') + 
  ylim(0, NA) +
  theme_bw()
})
```

To return to the main page, go here: https://acyeh-lab.github.io/stats/

